### ISSUE TITLE
Consider not using the `clldmpg` package

### ISSUE THREAD

**Issue by xrotwang** [aryamanarora/cdial#3]
I think you should only include `clld` here:
https://github.com/aryamanarora/cdial/blob/570bfbba7ed4d0d4dfd743ad9818b3b0b208682e/jambu/__init__.py#L40
The `clldmpg` package is meant to include the MPI SHH "corporate identity" in clld apps hosted on MPI SHH servers.

You probably don't want to link to MPI SHH from the footer of each page or include the MPI SHH imprint.

**Comment by aryamanarora** [comment]
Thanks for that, I have removed it (used one of the other CLLD apps as a template). Also aware that my CLLD structure is a little messy, still figuring out how to disentangle cognateset and parameter 😅

**Comment by xrotwang** [comment]
I guess for typical etymological dictionaries cognateset and parameter coincide. The reason we have both are datasets where cognatesets partition the words for the same meaning (parameter) or group words for (now) different meanings.

**Comment by aryamanarora** [comment]
Makes sense. I do have a field `gloss` in the CLDF, I'll see if I can extract parameter from there. Also, do you know if why [Values](http://jambu-clld.herokuapp.com/values) seems to timeout on Heroku? Is the server simply not able to handle the size of the query (170k entries)?

**Comment by xrotwang** [comment]
Regarding the performance of the unqualified `values` view (i.e. not narrowed down to just one language or parameter): The [default query](https://github.com/clld/clld/blob/2d698b75d2e6019619be6b01d09f0c77cb865af4/src/clld/web/datatables/value.py#L67-L75) is a bit unfortunate for large result sets. So in your case, the following change should do the trick:
```diff
diff --git a/jambu/jambu/datatables.py b/jambu/jambu/datatables.py
index ba2b02fe..27a83a19 100644
--- a/jambu/jambu/datatables.py
+++ b/jambu/jambu/datatables.py
@@ -1,6 +1,7 @@
 from sqlalchemy.orm import joinedload
 from clld.web import datatables
 from clld.web.datatables.base import LinkCol, Col, LinkToMapCol, IdCol
+from clld.db.models.common import Value, ValueSet
 
 from clld_glottologfamily_plugin.models import Family
 from clld_glottologfamily_plugin.datatables import FamilyCol
@@ -34,6 +35,17 @@ def f(x):
     return x.cognateset
 
 class Values(datatables.Values):
+    def base_query(self, query):
+        if not any([self.language, self.parameter, self.contribution]):
+            return query.join(ValueSet)\
+                .join(ValueSet.language)\
+                .join(ValueSet.parameter)\
+                .options(
+                    joinedload(Value.valueset).joinedload(ValueSet.language),
+                    joinedload(Value.valueset).joinedload(ValueSet.parameter),
+                )
+        return datatables.Values.base_query(self, query)
+
     def col_defs(self):
         if self.language:
             return [
```

This cut the load time from ~28s to 0.5s on my machine.

**Comment by aryamanarora** [comment]
This is great, thanks! Significantly faster on Heroku now, no more timeouts.
